version: '3'

services:

  #Database Mongo
  mongo:
    image: mongo:bionic
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - myNetwok
    restart: unless-stopped

  #mtg-toolbox site
  magic:
    build:
      context: ./
    image: matteosavina/mtg-toolbox-v1.0.4
    environment:
      - DBPATH=mongodb://mongo/mtg-toolbox
    ports:
      - 8090:8090
    networks:
      - myNetwok

volumes:
  mongo_data: # user defined network
networks:
  myNetwok:
    name: myNetwok
    driver: bridge
