version: '3'

services:

  #Database Mongo
  mongo:
    image: mongo:bionic
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - myNetwok
    restart: unless-stopped

volumes:
  mongo_data:
 # user defined network
networks:
  myNetwok:
    name: myNetwok
    driver: bridge
